# application.yml

spring:
  datasource:
    url: jdbc:mariadb://172.16.30.10:3306,172.16.30.11:3306/test_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: soyou
    password: soyou111
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # 개발 단계에서만 사용, 운영에서는 none 또는 validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect # MariaDB 10.x 버전에 맞는 Dialect 사용 (필요시 버전 확인 후 변경)
    show-sql: true # 실행되는 SQL 쿼리를 콘솔에 출력
server:
  port: 8080 # 선택 사항, 기본 8080
